---
offline_install: false
cluster: ceph

#Options are kernel or ganesha
ceph_nfs_server: "kernel" 
nfs_shared_storage_mountpoint: /mnt/nfsgw

# backend mode, either rados_kv,rados_ng, or rados_cluster
# Default ("rados_ng") is for for single gateway/active-passive use.
# "rados_cluster" is for active-active nfs cluster. Requires ganesha-grace-db to be initilaized
# rados_cluster is only supported with ganesha as the nfs server
nfs_rados_backend_driver: "rados_ng"

nfs_dynamic_exports: true
nfs_rados_backend: true

nfs_ceph_user: "admin"
nfs_log_file: "/var/log/ganesha/ganesha.log"
ceph_nfs_fs_root: "nfs"

nfs_keyring:
  - { name: client.nfs, caps: { mds: "allow r path=/, allow rwps path=/{{ nfs_fs_root }}", mon: "allow r", osd: "allow *" }, mode: "0600" }

nfs_ganesha_pool: 'nfs_ganesha'
nfs_export_namespace: "ganesha-export"
nfs_grace_namespace: "ganesha-grace"

pcmk_cluster_name: hacluster
pcmk_user: hacluster

nfs_floating_ip_address: '192.168.98.11'
nfs_floating_ip_cidr: '16'
nfs_floating_ip_interface : 'ens18'

ceph_nfs_mountd_port: 20048

nfs_ganesha_release_package_rpm: "centos-release-nfs-ganesha5"
