---
- name: remove default corosync.conf if present
  block:
    - name: check if corosync.conf exists
      stat:
        path: /etc/corosync/corosync.conf
      register: corosync_file

    - name: Read the first line of corosync.conf
      command: "head -n 1 /etc/corosync/corosync.conf"
      register: first_line
      changed_when: false
      ignore_errors: true
      when: corosync_file.stat.exists

    - name: Remove corosync.conf if the first line matches
      file:
        path: /etc/corosync/corosync.conf
        state: absent
      when: corosync_file.stat.exists and first_line.stdout == "# Please read the corosync.conf.5 manual page"

- name: Enable and start PCS daemon
  service:
    name: pcsd
    enabled: true
    state: started

- name: Enable corosync/pacemaker daemon
  service:
    name: "{{ item }}"
    enabled: true
    state: stopped
  loop:
    - corosync
    - pacemaker

- name: Generate a password for the user {{ pcmk_user }}
  set_fact:
    pcmk_password: "{{ ansible_machine_id | to_uuid }}"
  run_once: true
  when: pcmk_password is not defined

- name: Set user {{ pcmk_user }} password
  user:
    name: "{{ pcmk_user }}"
    password: "{{ pcmk_password | password_hash('sha512') }}"

- name: resolve hostnames
  set_fact: nfs_host_ips="{{ nfs_host_ips|default([]) + [ lookup('ip', '{{ item }}') ] }}"
  loop: "{{ ansible_play_batch }}"
  run_once: true

- name: Authenticate all nodes
  command: pcs host auth {{ nfs_host_ips | join(' ') }} -u "{{ pcmk_user }}" -p "{{ pcmk_password | quote }}"
  run_once: true
  args:
    creates: /var/lib/pcsd/tokens

- name: Setup message bus
  run_once: true
  command: pcs cluster setup {{ pcmk_cluster_name | quote }} {{  nfs_host_ips | join(' ') }}
  args:
    creates: /etc/corosync/corosync.conf

- name: Start the cluster
  command: pcs cluster start --all
  run_once: true

- name: Enable the cluster to start at boot time
  command: pcs cluster enable --all
  run_once: true

- name: Disable STONITH
  command: pcs property set stonith-enabled=false
  run_once: true

- name: Check for nfs_ip resource
  shell: "pcs resource show nfs_ip"
  failed_when: false
  run_once: true
  register: ip_resource_check

- name: Create Floating IP for NFS service
  command: pcs resource create nfs_ip ocf:heartbeat:IPaddr2 ip={{ nfs_floating_ip_address }} cidr_netmask={{ nfs_floating_ip_cidr }} nic={{ nfs_floating_ip_interface }} op monitor interval=10s
  run_once: true
  when: ip_resource_check.rc == 1

- name: set pcs tuning options
  command: pcs resource update nfs_ip op {{ item }} interval=0s timeout=5s
  run_once: true
  with_items:
    - start
    - stop

